M48
; DRILL file {KiCad (6.0.6)} date ma 04 jul 2022 20:15:53 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-04T20:15:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.6417Y-2.8543
X3.6417Y-5.8071
X5.0197Y-2.8543
X5.0197Y-5.8071
T0
M30
